# Generated by Django 5.0.6 on 2024-07-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_quoterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
