# Generated by Django 5.0.6 on 2024-07-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='services',
        ),
    ]
